/**
 * Generates typed ABI modules from the Foundry artifacts in ../out. Run after `forge build`
 * (wired as a predev/prebuild hook). The artifacts are the source of truth — the Order tuple is
 * too large to hand-transcribe safely, and `as const` gives viem full type inference.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url)); // demo/scripts
const repoRoot = resolve(scriptDir, "..", ".."); // repository root
const outDir = resolve(repoRoot, "out");
const genDir = resolve(scriptDir, "..", "src", "lib", "abis", "generated");

const CONTRACTS = [
  { file: "CctpAdapter.sol", name: "CctpAdapter", exportName: "cctpAdapterAbi" },
  { file: "OftAdapter.sol", name: "OftAdapter", exportName: "oftAdapterAbi" },
  { file: "FastFillConfig.sol", name: "FastFillConfig", exportName: "fastFillConfigAbi" },
];

// The generated modules are committed so the demo builds without Foundry (e.g. on Vercel).
// When the forge artifacts are absent but those committed copies exist, skip regeneration
// instead of failing the build.
const committedAbisExist =
  existsSync(resolve(genDir, "index.ts")) &&
  CONTRACTS.every((c) => existsSync(resolve(genDir, `${c.name}.ts`)));

if (!existsSync(outDir)) {
  if (committedAbisExist) {
    console.warn(
      `\n[gen-abis] Foundry artifacts not found at ${outDir}; using committed ABIs in ${genDir}.\n` +
        `  Run \`forge build\` in the repo root to regenerate them.\n`,
    );
    process.exit(0);
  }
  console.error(
    `\n[gen-abis] Foundry artifacts not found at ${outDir} and no committed ABIs in ${genDir}.\n` +
      `  Run \`forge build\` in the repo root before building the demo.\n`,
  );
  process.exit(1);
}

mkdirSync(genDir, { recursive: true });

const indexLines: string[] = [];
for (const c of CONTRACTS) {
  const artifactPath = resolve(outDir, c.file, `${c.name}.json`);
  if (!existsSync(artifactPath)) {
    console.error(`[gen-abis] Missing ${artifactPath}. Run \`forge build\` in the repo root.`);
    process.exit(1);
  }
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as { abi: unknown[] };
  const ts =
    `// AUTO-GENERATED by scripts/gen-abis.ts from out/${c.file}/${c.name}.json — do not edit.\n` +
    `export const ${c.exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(resolve(genDir, `${c.name}.ts`), ts);
  indexLines.push(`export { ${c.exportName} } from "./${c.name}";`);
  console.log(`[gen-abis] wrote ${c.name}.ts (${artifact.abi.length} ABI entries)`);
}

writeFileSync(resolve(genDir, "index.ts"), indexLines.join("\n") + "\n");
console.log("[gen-abis] done.");
